### ISSUE TITLE
named arguments and a splat

### ISSUE THREAD

**Issue by Yay295** [crystal-lang/crystal-book#102]
At the end of [this page](https://crystal-lang.org/docs/syntax_and_semantics/default_and_named_arguments.html) it says:

> When a method specifies a splat (explained in the next section), named arguments can't be used. The reason is that understanding how arguments are matched becomes very difficult; positional arguments are easier to reason about in this case.

but then in the [next section](https://crystal-lang.org/docs/syntax_and_semantics/splats_and_tuples.html) it says:

> Arguments past the splat argument can only be passed as named arguments.

Since it seems that named arguments *can* be used with a splat, I think the last paragraph of the first page I linked should either be removed, or changed to say that *positional* named arguments cannot be used with a splat but *non-positional* named arguments still can.

**Comment by HertzDevil** [comment]
Fixed by #462.
