### ISSUE TITLE
anything about spec?

### ISSUE THREAD

**Issue by Escapingbug** [crystal-lang/crystal-book#111]
I found that there is no content about spec, I have no idea about what spec is, is it like something about test module? Maybe it is better to have something about that. :)

**Comment by z64** [comment]
Spec is documented here, in the API documentations: https://crystal-lang.org/api/0.23.1/Spec.html

I don't think it's fitting for the Crystal Book, which primarily covers the core language - syntax, semantics, the compiler, etc - and not the standard library (which additionally, could change at any time).

**Comment by mverzilli** [comment]
Generally agree with @z64, but personally I'd like to see a little high level overview of testing in Crystal in the book. The compiler was written using TDD, so the specs lib is one of the first and more stable APIs in the std.

**Comment by straight-shoota** [comment]
Specs are not a part of the language, true. But `crystal spec` is also a compiler feature and as @mverzilli said it's a core library of the language.

I think it work's great as a *guide* as in #129
