### ISSUE TITLE
 Crystal installation on Debian be a bit more elaborate

### ISSUE THREAD

**Issue by enfageorge** [crystal-lang/crystal-book#113]
Installation on Debian unlike on Ubuntu raises a few issues that is unique to only itself. Like the need for apt-transport-https. I personally had to Google a lot to install crystal. Would be great if the documentation be made more elaborate to suit a beginner .

I am willing to work on it. Should I?

**Comment by mverzilli** [comment]
Hi @enfarose! I totally agree. In the past we rejected some PRs making this documentation more detailed because we felt like rather than growing the docs we should simplify the installation process itself, but that was a mistake because until we get to actually simplify the process users are left a bit on their own. 

So please if you have the time and energy to work on this, go ahead, it'll be appreciated!

**Comment by enfarose** [comment]
Will get on that ... thanks for the response

**Comment by enfarose** [comment]
PR given at 'added instruction for issues faced while installing on debian distro' 
#114

**Comment by enfarose** [comment]
If the needed packages were installed along with crystal on debian, then the above part wouldn't be necessary. Don't you think that is better?

**Comment by martinos** [comment]
I just tried to install the crystal on osx and I failed on 2 of my computers. After spending 3-4hrs I have abandoned.

After that I tried on Ubuntu and i followed the procedure and it failed too. But I have found that we need to install `libssl-dev`

I think that we should add the following to the following command to the documentation.

```
sudo apt-get install libssl-dev
```

**Comment by mverzilli** [comment]
@enfarose @martinos We introduced a number of changes in how we build Debian packages beginning with Crystal 0.24.1. In particular, we tried to make a better job of declaring dependencies. Can you give it a try and tell us whether you're still experiencing difficulties?

**Comment by straight-shoota** [comment]
Closing this until there is some feedback on what still needs fixing.
