### ISSUE TITLE
Information about `@@classvariable` inheritance outdated

### ISSUE THREAD

**Issue by Byron** [crystal-lang/crystal-book#12]
In the [book it says](https://crystal-lang.org/docs/syntax_and_semantics/class_variables.html) that the following code does not work:
```crystal
class Parent
  @@counter = 0
end

class Child < Parent
  def self.counter
    # Error, can't infer the type of class variable
    # '@@counter' of Child
    @@counter
  end
end
```

However, since [v18](https://crystal-lang.org/2016/06/14/crystal-0.18.0-released.html#class-variables-are-now-inherited) this is not the case anymore.

**Comment by asterite** [comment]
Thank you! In my mind I did this change earlier, but maybe it was for another topic...
