### ISSUE TITLE
Documentation is light around the property keyword

### ISSUE THREAD

**Issue by robacarp** [crystal-lang/crystal-book#130]
While working with the amber framework, specifically reading the [granite orm code](https://github.com/amberframework/granite-orm/blob/347c2153e7b2491c00b6b8648222ce354b83a763/src/adapter/base.cr#L8) I ran across the property keyword.

[Searching the language docs](https://crystal-lang.org/docs/?q=property) I came up empty with much of an explanation as to what is going on. The search results point to two articles which use the keyword (Attributes and Structs) and three articles matched on stemming ("properties") but still did not give a concrete definition of the keyword and its purpose.

[Crystal for Rubyists](https://github.com/crystal-lang/crystal/wiki/Crystal-for-Rubyists#available-keywords) does clarify the meaning with it's table comparing it to Ruby's #attr_accessor, but I don't see this mirrored in the official documentation anywhere.

This seems like a hole in the documentation but I'd like to get a sign off from someone marked as a contributor about where and what the documentation should say about the keyword before submitting a doc pull request.

**Comment by straight-shoota** [comment]
`property` is not a keyword but a macro defined on `Object`. Thus, it's not part of the language but Crystal's standard library.

It is actually quite well documented in the [API docs](https://crystal-lang.org/api/0.23.1/Object.html#property%28%2Anames%29-macro).

But it might make sense to mention these macros on the page about *Methods and instance variables*.

**Comment by robacarp** [comment]
Great, that documentation is exactly what I was looking for, thanks.

The [Methods and instance variables](https://crystal-lang.org/docs/syntax_and_semantics/methods_and_instance_variables.html) page would be a fine place to provide a paragraph and terse example pointing back to the standard library docs. 

I'd be happy to write and submit a pull request to provide a little documentation around the pattern. I'm not well enough acquainted with the docs to know, are there any examples of this cross linking that I can emulate to augment the docs?
