### ISSUE TITLE
Debian 9 + WSL *fixes*

### ISSUE THREAD

**Issue by Wulfklaue** [crystal-lang/crystal-book#134]
The following command are needed for installing on Debian 9:

```
sudo apt-get install apt-transport-https dirmngr libssl-dev zlib1g-dev gcc
```

> dirmngr is used by the current setup.sh script but is not default installed. Without this the shell script breaks and you can not even install crystal as a trusted source.

> apt-transport-https and libssl-dev  are used by the webserver example compilation
> gcc is needed for the linker, no gcc = error during compilation
> zlib1g-dev ... fixes compile error.

With any of them missing, its impossible to compile crystal on a fresh installed Debian 9 installation.

For WSL on Windows ( This may also apply to the Ubuntu installation seeing as WSL = Ubuntu ):

```
sudo apt-get install libssl-dev
```

If they are missing from the setup.sh script, Crystal will fail to install or compile for instance the web example on Debian/WSL/Ubuntu.

**Comment by robacarp** [comment]
This seems like the detail needed to address #113

**Comment by mverzilli** [comment]
@Wulfklaue @robacarp We introduced some changes in how we build Debian packages beginning with 0.24.1. In particular, now dependencies are properly declared in the package manifest. Can you try again and tell us if you still need any of those explicit installs?

**Comment by Wulfklaue** [comment]
@mverzilli 

Tried a fresh Crystal install on my Debian 9 server. So far everything is working perfectly.
