### ISSUE TITLE
Integer Literals Should Give Value Ranges, not Bit Size

### ISSUE THREAD

**Issue by HCLarsen** [crystal-lang/crystal-book#137]
Right now it says "There are four signed integer types: Int8, Int16, Int32 and Int64, being able to represent numbers of 8, 16, 32 and 64 bits respectively."

I think it would be much better to show the range of values that can be represented with those classes. It makes for a far better explanation. I'm happy to write the revision myself, I just want to run it by the core team first.

**Comment by HCLarsen** [comment]
Something like this is what I'm thinking:

There are four signed integer types: [Int8](http://crystal-lang.org/api/Int8.html)(, [Int16](http://crystal-lang.org/api/Int16.html), [Int32](http://crystal-lang.org/api/Int32.html) and [Int64](http://crystal-lang.org/api/Int64.html), being able to represent numbers in the ranges of −128 to 127, −32,768 to 32,767, −2,147,483,648 to 2,147,483,647 and −9,223,372,036,854,775,808 to 9,223,372,036,854,775,807 respectively.

**Comment by bew** [comment]
I think that we should keep the bit size information, but give a hint about the possible value range.

**Comment by HCLarsen** [comment]
The bit size can easily be inferred from the class name. After all, it's right there in the class name. The value range on the other hand, not really. Now maybe some very experienced developers have those ranges memorized, but documentation needs to cater to people of all experience levels. 

When I was young, learning C as my first compiled language, the documentation there did show the difference between an Int and a Long Int, and that was invaluable to me learning how to use them.

**Comment by HCLarsen** [comment]
I'm not against a table, but with the large numbers in the higher ranges, it doesn't get a bit unruly. Take a look:

Length  | Signed | Signed Values | Unsigned | Unsigned Values
 ---------- | -----------: | -----------: |-----------: | -----------: |
8       |   Int8   | -128-127 | UInt8 | 0-255
16       |   Int8   | −32,768-32,767-32,767| UInt8 | 0-65,535
8       |   Int8   | −2,147,483,648-2,147,483,647-2,147,483,647 | UInt8 | 0-4,294,967,295
8       |   Int8   | −9,223,372,036,854,775,808-9,223,372,036,854,775,807 | UInt8 | 0-18,446,744,073,709,551,615

**Comment by HCLarsen** [comment]
Unless we separate the signed and unsigned integers into separate rows or tables.

**Comment by RX14** [comment]
Yes of course we should have each crystal type be one row, not one bit length ( especially when you're saying but length is fairly unimportant)

**Comment by HCLarsen** [comment]
I'm not saying that bit length is unimportant, I'm saying that it can be easily inferred from the reader by the name of the class itself.

**Comment by asterite** [comment]
Specially if we include the formula. We recently added Int128 and UInt128. I see no reason why mentioning the value `340282366920938463463374607431768211455` will be important. It seems like a random number. But if we say "it's 2**n - 1" where n is the number of bits, it makes more sense.

**Comment by HCLarsen** [comment]
So, I've got two ideas. First is this:

There are four signed integer types: [Int8](http://crystal-lang.org/api/Int8.html), [Int16](http://crystal-lang.org/api/Int16.html), [Int32](http://crystal-lang.org/api/Int32.html),[Int64](http://crystal-lang.org/api/Int64.html).

There are also four unsigned integer types: [UInt8](http://crystal-lang.org/api/UInt8.html), [UInt16](http://crystal-lang.org/api/UInt16.html), [UInt32](http://crystal-lang.org/api/UInt32.html), [UInt64](http://crystal-lang.org/api/UInt64.html).

Class | Length  | Values
 ---------- | -----------: | -----------: |
Int8  |    8       |    -128-127 | 
Int16  | 16 | −32,768-32,767-32,767| 
Int32 | 32  | −2,147,483,648-2,147,483,647-2,147,483,647 | 
Int64   |  64 | −9,223,372,036,854,775,808-9,223,372,036,854,775,807 | 
UInt8 | 8 |  0-255
UInt16 | 16 | 0-65,535
UInt32 | 32 |  0-4,294,967,295
UInt64 | 64 | 0-18,446,744,073,709,551,615

**Comment by HCLarsen** [comment]
Or, the second one, which I think is better: 

There are four signed integer types, and for unsigned integer types:

Class | Length  | Values
 ---------- | -----------: | -----------: |
[Int8](http://crystal-lang.org/api/Int8.html)  |    8       |    -128-127 | 
[Int16](http://crystal-lang.org/api/Int16.html)  | 16 | −32,768-32,767-32,767| 
[Int32](http://crystal-lang.org/api/Int32.html) | 32  | −2,147,483,648-2,147,483,647-2,147,483,647 | 
[Int64](http://crystal-lang.org/api/Int64.html)   |  64 | −9,223,372,036,854,775,808-9,223,372,036,854,775,807 | 
[UInt8](http://crystal-lang.org/api/UInt8.html) | 8 |  0-255
[UInt16](http://crystal-lang.org/api/UInt16.html) | 16 | 0-65,535
[UInt32](http://crystal-lang.org/api/UInt32.html) | 32 |  0-4,294,967,295
[UInt64](http://crystal-lang.org/api/UInt64.html) | 64 | 0-18,446,744,073,709,551,615

**Comment by mverzilli** [comment]
What about splitting `Values` in two columns, one for the lower bound and the other for the upper bound? I think it would help clarify the ranges

**Comment by HCLarsen** [comment]
Would that look so good with the Unsigned Ints? For those, the lower bound is just 0.

I do think that at the very least, I should replace the dash with the word "to."

**Comment by mverzilli** [comment]
Yes, even if the lower bound is 0 in all unsigned cases, tabulating it will make it a lot easier to parse.

**Comment by straight-shoota** [comment]
I'd suggest something like this.
With a proper HTML table it could even be made a bit nicer.
Numerical values should be in individual columns and monospaced to make it easily comparable.

| Class  | Length | Lowest Value                            | Highest Value                       |
| ---    |   ---: |                              ---:| ---:                        |
| Int8   | `8`      | `-128`                             | `127`                         |
| Int16  | `16`     | `−32,768-32,767`                   | `32,767`                      |
| Int32  | `32`     | `−2,147,483,648`                   | `2,147,483,647-2,147,483,647` |
| Int64  | `64`     | `−9,223,372,036,854,775,808`       | `9,223,372,036,854,775,807`   |
| UInt8  | `8`      | `0`                                | `255`                         |
| UInt16 | `16`     | `0`                                | `65,535`                      |
| UInt32 | `32`     | `0`                                | `4,294,967,295`               |
| UInt64 | `64`     | `0`                                | `18,446,744,073,709,551,615`  |

**Comment by asterite** [comment]
Can somebody answer what's the point of including values like `18,446,744,073,709,551,615` in the docs instead of `2**64-1`?

**Comment by mverzilli** [comment]
I'm ok with either alternative.

**Comment by HCLarsen** [comment]
@asterite readability is the point. The full out number is easier for the average human being to understand than `2**64 - 1`.

**Comment by HCLarsen** [comment]
@straight-shoota what about the links to the individual class pages. Should I include those in the table as per the second example I gave, or do you prefer it in a paragraph above the table?

**Comment by straight-shoota** [comment]
For 8 and 16 bit the raw value might be easier but what do is to understand about `18,446,744,073,709,551,615`? Doesn't help much.
People who read such documents should be able to easily find a way to calculate or look up the exact values if needed.

I guess I'd prefer the variant with links in the table. DRY.

**Comment by HCLarsen** [comment]
Good documentation doesn't lead its readers to look things up elsewhere. If you can easily explain it within your documentation, that's exactly what you should do.

**Comment by asterite** [comment]
Another reference, Java this time: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

For small values they show the limits, then they use the 2**n approach.

By the way, the average human is not a programmer and will not read these docs. And the average programmer knows math :-)

Anyway, I'm fine with either approach. Just notice that when we'll add Int128 it will look like this:

| Class  | Length | Lowest Value                            | Highest Value                       |
| ---    |   ---: |                              ---:| ---:                        |
| Int8   | `8`      | `-128`                             | `127`                         |
| Int16  | `16`     | `−32,768`                   | `32,767`                      |
| Int32  | `32`     | `−2,147,483,648`                   | `2,147,483,647-2,147,483,647` |
| Int64  | `64`     | `−9,223,372,036,854,775,808`       | `9,223,372,036,854,775,807`   |
| Int128 | `128` | `-170,141,183,460,469,231,731,687,303,715,884,105,728` | `170,141,183,460,469,231,731,687,303,715,884,105,727` |
| UInt8  | `8`      | `0`                                | `255`                         |
| UInt16 | `16`     | `0`                                | `65,535`                      |
| UInt32 | `32`     | `0`                                | `4,294,967,295`               |
| UInt64 | `64`     | `0`                                | `18,446,744,073,709,551,615`  |

It doesn't fit this conversation, I'm not sure it will either fit the docs page. Plus I can introduce a typo, maybe write `170,141,183,460,469,232,731,687,303,715,884,105,727` and you won't notice it. Nobody will read those long numbers with attention.

**Comment by HCLarsen** [comment]
Programming enters more and more people's live with every passing year. The average person needs to be considered when writing good documentation. Elitism has no place here.

**Comment by HCLarsen** [comment]
More and more people are getting exposed to programming by the year, which means that it's entering the average person's life. What's more, consider that Crystal has the potential to be a great language for beginner developers, who won't be inclined to do 2**64 - 1 in their head.

**Comment by HCLarsen** [comment]
I can see some logic in using exponents to represent the larger numbers, such as the 64 and eventual 128 bit Integers. As you say, a typo in a string of digits that long is likely to go unnoticed. However for the 8, 16 and 32 bits, I'm vehement that the actual ranges should be used.

**Comment by HCLarsen** [comment]
I disagree with Oracle's choice. The 32bit bounds are small enough that it should be shown in literal format. Remember, the point is readability. Exponential formats don't offer readability, as someone who's not experienced in static typing isn't going to look at 2^32 - 1 and immediately register it as being ~ 2b. 

64 bits, I'll go with, because at that point, the literal representation gets a bit unruly. However, the literal value for 32 bits is easy to show.

**Comment by HCLarsen** [comment]
There are four signed integer types, and four unsigned integer types:

Class | Length  | Minimum Value | Maximum Value
 ---------- | -----------: | -----------: |-----------: |
[Int8](http://crystal-lang.org/api/Int8.html)  | 8       | -128 | 127 | 
[Int16](http://crystal-lang.org/api/Int16.html)  | 16 | −32,768 | 32,767| 
[Int32](http://crystal-lang.org/api/Int32.html) | 32  | −2,147,483,648 | 2,147,483,647| 
[Int64](http://crystal-lang.org/api/Int64.html)   |  64 | −2<sup>63</sup> | 2<sup>63</sup> - 1 | 
[UInt8](http://crystal-lang.org/api/UInt8.html) | 8 |  0 | 255
[UInt16](http://crystal-lang.org/api/UInt16.html) | 16 | 0 | 65,535
[UInt32](http://crystal-lang.org/api/UInt32.html) | 32 |  0 | 4,294,967,295
[UInt64](http://crystal-lang.org/api/UInt64.html) | 64 | 0 | 2<sup>64</sup> - 1 |

**Comment by mverzilli** [comment]
@HCLarsen that's good enough.
