### ISSUE TITLE
Fresh variables example doesn't work anymore.

### ISSUE THREAD

**Issue by yxhuvud** [crystal-lang/crystal-book#142]
The `fresh_vars_sample(*names)`  on https://crystal-lang.org/docs/syntax_and_semantics/macros/fresh_variables.html does not output 
```
# Declaring: __temp_255
# Declaring: __temp_256
# Declaring: __temp_257
# __temp_255: 0
# __temp_256: 1
# __temp_257: 2
```
as the example claims, but instead output 
```
Declaring: %name{index}
Declaring: %name{index}
Declaring: %name{index}
%name{index}: 0
%name{index}: 1
%name{index}: 2
```
(crystal 23)

**Comment by mverzilli** [comment]
Did we break this on purpose? I'm not finding any mention to this breaking change in the changelog, so wondering if we should change the documentation or file an issue.

**Comment by straight-shoota** [comment]
I don't think this should have worked in the first place. Why would a StringLiteral `"%name{index}"` expanded to a temp variable?

**Comment by yxhuvud** [comment]
@straight-shoota  It works with symbols though, :%name{index} will generate a unique symbol.

**Comment by straight-shoota** [comment]
Ah yes, I see. Nice. Then the example code should probably be updated to:

```crystal
macro fresh_vars_sample(*names)
  # First declare vars
  {% for name, index in names %}
    print "Declaring: ", :%name{index}, '\n'
    %name{index} = {{index}}
  {% end %}

  # Then print them
  {% for name, index in names %}
    print :%name{index}, ": ", %name{index}, '\n'
  {% end %}
end

fresh_vars_sample a, b, c
```

**Comment by yxhuvud** [comment]
Hmm, actually, not so nice I had hoped. 

```
macro fresh_vars_sample(sym)
    p  {{sym}}%name
end

3.times do
  fresh_vars_sample :a
end
```
=> 
```
:a__temp_22
:a__temp_22
:a__temp_22
```
I can see why it works the way it does though.

**Comment by asterite** [comment]
It's just a bug in the compiler. Some code was added to correctly parse `"...%s..."` inside string literals and that broke this.

**Comment by straight-shoota** [comment]
@asterite Does this need a bugfix in the compiler or is updating the documentation enough?

**Comment by erdian718** [comment]
> @asterite Does this need a bugfix in the compiler or is updating the documentation enough?

I think the documentation should be updated first, as this is important for beginners.
I ran into the same confusion while reading this part of the documentation until I saw this issue.
