### ISSUE TITLE
What is the Repo for the Official pt-br translation of the docs?

### ISSUE THREAD

**Issue by andrealmar** [crystal-lang/crystal-book#150]
Hi,

I'm willing to contribute helping to translate the Official Docs to Brazilian Portuguese (pt-br). Where can I find the repo for that translation http://br.crystal-lang.org/ ?

**Comment by mverzilli** [comment]
Hi @andrealmar! Great to hear that! The Brazilian Portuguese repo is here: https://github.com/crystal-lang-br/crystal-lang-br

Thank you for your collaboration! 🙏
