### ISSUE TITLE
Consider mounting this book under /reference instead of /docs

### ISSUE THREAD

**Issue by mverzilli** [crystal-lang/crystal-book#173]
Now that we're referring to this book as "language reference" instead of "documentation" (https://github.com/crystal-lang/crystal-book/issues/78), we could reflect the change in the URI. This will hopefully reduce a frequent source of confusion for newcomers to the community: many expect to find under `/docs` what we put under `/api`.

**Comment by RX14** [comment]
We should redirect `/docs` to `/reference` though for quite a long time. It's still used in many places.

**Comment by straight-shoota** [comment]
Yes, but the root path `/docs` could become a overview page linking to language reference, api docs, knowledge base, maybe tutorials at some point...

**Comment by straight-shoota** [comment]
@mverzilli How can we proceed with this?

**Comment by RX14** [comment]
:+1: getting this renamed is far better done sooner rather than later.

**Comment by mverzilli** [comment]
Nothing preventing us from doing it (agree with RX14 that redirecting /docs is sensible). 

I guess we'd need to change this to "/reference": https://github.com/crystal-lang/crystal-book/blob/master/.travis.yml#L21

And then set up the redirect from AWS. @bcardiff?

**Comment by bcardiff** [comment]
The redirect can be setup once. I though we wanted to use `/book` instead of `/reference`. Both work.
The `/doc` index page will live in the website.

**Comment by straight-shoota** [comment]
It's referred to as the *language reference* which would fit nicely with mounting under `/reference`. Never heard `/book` mentioned until now. I guess it would be fine, too.

**Comment by RX14** [comment]
I think eventually we will have a "crystal book" which is organised more like a walkthrough, introducing concepts in a narative order and then expanding on them later. So `/book`, `/reference` and `/api`.

**Comment by bcardiff** [comment]
I've just update s3/cloudfront configuration of the website.
* `/docs/*` is redirected to `/reference/*` as 301
* `/docs` is redirected to `/reference` as 302 so we can have a docs page in the website with the desired introduction to api & reference.

```json
{
  "IndexDocument": {
    "Suffix": "index.html"
  },
  "ErrorDocument": {
    "Key": "404.html"
  },
  "RoutingRules": [
    {
      "Condition": {
        "KeyPrefixEquals": "docs/",
        "HttpErrorCodeReturnedEquals": "404"
      },
      "Redirect": {
        "HttpRedirectCode": "301",
        "ReplaceKeyPrefixWith": "reference/",
        "Protocol": "https",
        "HostName": "crystal-lang.org"
      }
    },
    {
      "Condition": {
        "KeyPrefixEquals": "docs",
        "HttpErrorCodeReturnedEquals": "404"
      },
      "Redirect": {
        "HttpRedirectCode": "302",
        "ReplaceKeyPrefixWith": "reference",
        "Protocol": "https",
        "HostName": "crystal-lang.org"
      }
    }
  ]
}
```
