### ISSUE TITLE
Add documentation for working with shards

### ISSUE THREAD

**Issue by GloverDonovan** [crystal-lang/crystal-book#174]
I believe it would be beneficial if the crystal reference had a section that explains how to use shards in a project. I tried searching `shards update`, for example, and couldn't find any relevant information.

It may also help to:

1. Add a man page for shards. This makes sense since there's already one for crystal (consistency).
2. Add a brief description about each option to `shards --help`. This would also make it consistent with `crystal --help`.

My initial question: What is the difference between `shards update` and `shards install`? When I tested them, they both functioned identically to me so I wanted to know what they actually do.

**Comment by z64** [comment]
More info on `shards` can be found in its repo, specifically your question:
> Simply run `shards install` to install your dependencies (or `crystal deps install`), which will lock your dependencies into a `shard.lock` file, which you should check into version control, so further install will always install the locked versions, achieving reproducible installations across computers.

Whereas, `update` will also install and make `shard.lock`, but won't consider an *existing* `shard.lock` and check for updates that still fall within the range of your dependency requirements (`~> 1.1`, etc)
https://github.com/crystal-lang/shards#install

**Comment by GloverDonovan** [comment]
@z64 Thanks for your reply! I understand how they're different now. To summarize:

- `shards install` considers `shard.lock` when determining which versions to use
- `shards update` does not consider `shard.lock` when determining which versions to use

I understand now why this distinction is so useful. Thanks again.

**Comment by RX14** [comment]
@GloverDonovan yes and in addition it's called `update` because it updates `shard.lock` with the new versions if they change.

**Comment by straight-shoota** [comment]
Update: Shards manpage should be installed by default. In the next release, manpage and `shards --help` get a large expansion from crystal-lang/shards#227

Just have to copy that into a markdown page.
