### ISSUE TITLE
Add documentation for `finished` module hook to hooks page

### ISSUE THREAD

**Issue by robacarp** [crystal-lang/crystal-book#188]
The crystal book chapter on hooks doesn't include `finished`:

> Special macros exist that are invoked in some situations as hooks: inherited, included, extended and method_missing.

Should it?

**Comment by asterite** [comment]
I don't know, `finished` feels to me like a dirty hack, and also gathering stuff in compile-time constants. Plus it doesn't work well regarding the type of instance vars (they are not available in the `finished` hook). I think `finished` and general attributes need some thoughts first.

**Comment by robacarp** [comment]
Great, thanks @asterite

**Comment by RX14** [comment]
If it's in the language, it should be documented. Whether it should be in the language is a different issue (literally).

**Comment by r00ster91** [comment]
This can be closed now since #153 is merged.

**Comment by mverzilli** [comment]
Thanks!
