### ISSUE TITLE
Elaborate on the concept of "bang!" methods

### ISSUE THREAD

**Issue by sudo-nice** [crystal-lang/crystal-book#204]
At the very bottom of the page [Exception Handling][1] the concept of using "question?" methods are elaborated partially. The description of other application of "question?" methods could be found in [Crystal for Rubyists][2] manual.

**To sum these two up:**

| Concept to communicate | Examples | Implies a non-question variant |
| --- | --- | :--: |
| Return `nil` instead of rising an exception when trying to retrieve inexistent item from a collection (Tuple, NamedTuple, Array, Hash). | `Tuple#[]?` `Array#first?`, `Hash[key]?` | Yes, always |
| Return `Bool` value indicating whether an assumption is correct. | `String#includes?(item)`, `Enumerable#includes?(item)`, `Enumerable#all?` | No |

---

**And what about "bang!" methods?**
I haven't dig too deep, so that's what I've got:

| Concept to communicate | Examples | Implies a non-bang variant |
| --- | --- | :--: |
| Raise an Exception unless the assumption is correct (kind of inversion of the first use-case from the table above). | `Array#not_nil!` | No |
| More dangerous version of a non-bang counterpart method. So, bang method exists only if there is already a non-bang, less drastic method. | `Array#compact!`, `Hash#merge!` | Yes, always |

*Maybe it worth to reflect the bang-method concept in crystal-book?*

[1]: https://github.com/crystal-lang/crystal-book/blob/master/syntax_and_semantics/exception_handling.md
[2]: https://github.com/crystal-lang/crystal/wiki/Crystal-for-Rubyists

**Comment by RX14** [comment]
Bang methods have always been a bit fuzzy in their usage. It's definitely worth mentioning that for standard collections like `Array` and `Hash` a bang method *always* indicates that the method will mutate `self` but i'm not sure that there are many concrete rules on bang usage outside of those classes.

**Comment by sudo-nice** [comment]
@RX14
Consider these examples:
```
Array#not_nil! # doesn't always mutate self
Array#pop      # does mutate self
```

So, maybe bang methods it's not about mutating `self` at all. Most time they mutate, but that is not the rule.

Ruby has faced that [controversy](https://stackoverflow.com/a/612196) too. Particularly, Matz [stated](https://www.ruby-forum.com/topic/176830#773946):

> The bang (!) does not mean "destructive" nor lack of it mean non destructive either.  The bang sign means "the bang version is more dangerous than its non bang counterpart; handle with care".  Since Ruby has a lot of "destructive" methods, if bang signs follow your opinion, every Ruby program would be full of bangs, thus ugly.

Maybe, Crystal could have more "crystal" guides.

**Comment by RX14** [comment]
@sudo-nice `not_nil!` is on `Object`, not `Array`. I was talking about the collection classes only. And yes, we'd have to clarify that not all mutating methods had bangs. This is because some methods "obviously" mutate (i.e. `pop`).

**Comment by sudo-nice** [comment]
> i'm not sure that there are many concrete rules on bang usage outside of those classes

After more deep diving into Crystal, I realized that.
