### ISSUE TITLE
Document usage of command line arguments 

### ISSUE THREAD

**Issue by Heaven31415** [crystal-lang/crystal-book#223]
There is no information in the book about how to pass command line arguments to the program. Description of **argc** and **argv** arguments is also missing. This is pretty basic, but also pretty important.

If someone wants to document this, you can start by reading: [API docs](https://crystal-lang.org/api/0.24.2/toplevel.html#main%28argc%3AInt32%2Cargv%3APointer%28Pointer%28UInt8%29%29%29-class-method)

**Comment by straight-shoota** [comment]
Process arguments are a part of the runtime, not the language. Thus it belongs to the API docs, not the language reference.

The API docs for `ARGV` can certainly be improved and it would it would be a great enhancement to have a guide about this.

**Comment by straight-shoota** [comment]
There is now a getting started guide on command line applications which covers using `OptionParser`, which is a good choice for many applications.
