### ISSUE TITLE
Missing documentation of 'finished'  and other builtin macros/hooks

### ISSUE THREAD

**Issue by colonlc** [crystal-lang/crystal-book#228]
Someone suggested me the `finished` macro in my issue #5889 over on crystal-lang/crystal, which I did not know of before because it is not documented here. So please include a full list of builtin macros and hooks.

**Comment by RX14** [comment]
We have a macros/hooks section already but it just doesn't include `finished`.

**Comment by colonlc** [comment]
But as you said, it is not included. So please make a *full* list of hooks :).

**Comment by r00ster91** [comment]
This can be closed now since #153 is merged.

**Comment by mverzilli** [comment]
Thanks!
