### ISSUE TITLE
Use new Gitbook version

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal-book#237]
https://www.gitbook.com/ has been updated! :tada: 

![screenshot_20180507_211418](https://user-images.githubusercontent.com/3067335/39734166-9b33f9b0-523b-11e8-8c2a-b748caea886e.png)

The new gitbook ui looks pretty nice :heart: 

![screenshot_20180507_210750](https://user-images.githubusercontent.com/3067335/39733952-b4cc300a-523a-11e8-9ac8-7df16198c57c.png)

Can we update https://crystal-lang.org/docs/ to use this new version?

/cc @asterite @straight-shoota @bcardiff @mverzilli

**Comment by faustinoaq** [comment]
> i vote yes, but only under 1 condition:
> full text searching like we have already on master =]

@girng This is only for https://crystal-lang.org/docs/ **this page already uses gitbook**

**Comment by straight-shoota** [comment]
This new version is for the hosted service provided on gitbook.com. This repo uses the [open source edition](https://github.com/GitbookIO/gitbook) which has been deprecated.

I'd vote to close this in favor of #261.

**Comment by j8r** [comment]
Rust has [mdBook](https://github.com/rust-lang-nursery/mdBook) – Like Gitbook but implemented in Rust.

**Comment by straight-shoota** [comment]
Resolved by #433
