### ISSUE TITLE
Editor support

### ISSUE THREAD

**Issue by amitsaha** [crystal-lang/crystal-book#24]
Hey all, so far I have seen a vim plugin and a sublime text plugin. I think there should be a section on editor support in the docs. Happy to write it in.

**Comment by mverzilli** [comment]
I don't think that belongs here, at least currently. Most of the plugins just work partially and sometimes they remain broken for quite a long time when there's some breaking change, so this section will be doomed to get out of date. Besides, none of those editors are under the `crystal-lang` umbrella, so if they break there's not much we can do to follow up. I think until the whole ecosystem settles down the list we have in the wiki has the right level of commitment: https://github.com/crystal-lang/crystal/wiki#editor-support
