### ISSUE TITLE
wrong definition of type inference of the branches in if

### ISSUE THREAD

**Issue by BenDietze** [crystal-lang/crystal-book#241]
While reading **if** found this:

_After an if, a variable’s type depends on the type of the expressions used in both branches._

_Note that if a variable is declared inside one of the branches but not in the other one, at the end of the if it will also contain the Nil type._

But, its not clear and morely wrong. It could better be some of:

_Note that at the end of if the type of if contains at minimum the type of both, the if and the else branch, or of all available branches. If there is only a if branch, the else branch contains the Nil type._

```crystal
if some_condition
  a = 1
end
# => Int32 | Nil

if some_condition
  a = 1
else
  b = 'x'
end
# => Char | Int32

if some_condition
  a = 1
elsif some_other_condition
  b = 'x'
else
  c = "somewhat"
end
# => Char | Int32 | String
```

_Please note:_ thats my maximum english amount :)

**Comment by straight-shoota** [comment]
This paragraph is not about the type of the `if` expression but about variables assigned inside the branches.

To illustrate:
```cr
if some_condition
  a = 1
end
a # => Int32 | Nil

if some_condition
  a = 1
else
  b = 'x'
end
a # => Int32 | Nil
b # => Char | Nil

if some_condition
  a = 'y'
else
  a = 'x'
end
a # => Char
```

**Comment by BenDietze** [comment]
You are right 👍

I think _if_ is a little bit special in type inference because of this, but ok, seems i have just overlooked the explained variable inferences. Your example is very readable, little bit easier to follow than that between _After an if..._ and _Note that..._

**Comment by straight-shoota** [comment]
The docs page should probably be edited for being better understandable.

**Comment by BenDietze** [comment]
Just a little bit of syntactic sugar :)

👍
