### ISSUE TITLE
Partial search for page title not always working

### ISSUE THREAD

**Issue by mmKALLL** [crystal-lang/crystal-book#242]
Searching `visi`, `visib`, or `visibility` in the top-left corner search box produces the following three results: Visibility, The Program, and Macros.

However, searching for `visibi`, `visibil`, `visibili` or `visibilit` returns no results.

Additionally, searching for `the` does not return The Program, despite the word "the" appearing in the title, URL, and text.

I expected all searches `visi` through `visibility` to produce the same three results, and `the` to find The Program, possibly along with other pages.

Not quite sure what exactly would cause this, or whether the issue is on the GitBook side of things.  
Willing to investigate/fix if someone can point me in the right direction. Thanks!

**Comment by RX14** [comment]
This is definitely a gitbook bug, not sure we've updated our gitbook version in a while.

**Comment by straight-shoota** [comment]
Fixed by #433
