### ISSUE TITLE
The documentation left menu crashes when you hit a link

### ISSUE THREAD

**Issue by mrkaspa** [crystal-lang/crystal-book#28]
![screen shot 2016-09-24 at 8 04 02 pm](https://cloud.githubusercontent.com/assets/764271/18812205/1d0cd23e-8292-11e6-80db-e1341f64c90c.png)

**Comment by RX14** [comment]
It appears to work fine to me. Can you give more details?

**Comment by mverzilli** [comment]
Closing until we get more details.
