### ISSUE TITLE
Document Gitlab Shard process

### ISSUE THREAD

**Issue by KCErb** [crystal-lang/crystal-book#286]
Hi all,

I just published three shards to gitlab (https://gitlab.com/crystal-symmetry) and learned a lot in the process. I think the documentation on releasing a shard is a bit Github / Travis centric and would like to see the docs refactored a bit.

Right now the guide reads as a tutorial which is nice but different from the rest of the book. Perhaps one page could outline the basic rules and another could be the walkthrough. The end of the walkthrough could then fork into a section for github and a section for gitlab.

I'm happy to do a writeup but don't want to waste my time if there is a reason for being focused on Github or if this kind of refactor doesn't interest you guys.

**Comment by straight-shoota** [comment]
Resolved by #299
