### ISSUE TITLE
Document Installation on SUSE OSes using Zypp

### ISSUE THREAD

**Issue by kinxer** [crystal-lang/crystal-book#288]
I was able to extrapolate from the ["On RedHat and CentOS" installation page](https://crystal-lang.org/docs/installation/on_redhat_and_centos.html) and a recent experience installing [Atom](https://flight-manual.atom.io/getting-started/sections/installing-atom/#suse-zypp) to install Crystal on openSUSE Tumbleweed, but if I had not had that experience I (as a relatively new user of SUSE OSes) would have had significant trouble installing Crystal without building from source.

Given that I was able to extrapolate from the "On RedHat and CentOS" page, it shouldn't be too difficult to write a similar description using Zypp instead of Yum.

EDIT: This is addressed by #245 (and #246)

**Comment by straight-shoota** [comment]
Fixed in #325
