### ISSUE TITLE
Inappropriate usage of mathematics symbols in `range`

### ISSUE THREAD

**Issue by Paalon** [crystal-lang/crystal-book#291]
In [mathematics](https://en.wikipedia.org/wiki/List_of_mathematical_symbols), typically `[`, ` ]` are the symbols for closed itervals and `(`, `)` are for open intervals: `[a, b] := {x ∈ R | a ≤ x ≤ b}` and `[a, b) := {x ∈ R | a ≤ x < b}` but in this document uses it with different meaning. 
```crystal
x..y  # an inclusive range, in mathematics: [x, y]
x...y # an exclusive range, in mathematics: [x, y)
```
It's so confusing. It should be replaced to `{r ∈ Z | x ≤ r ≤ y}` and `{r ∈ Z | x ≤ r < y}`, or `{x, x + 1, …, y - 1, y}` and `{x, x + 1, …, y - 1}`, or deleted the sentence (because there is the examples of range in crystal code in the document so it is not essential).

**Comment by RX14** [comment]
@Paalon integer intervals exist, I don't see why this doesn't make sense in context.

**Comment by Paalon** [comment]
I cannot understand what you mean. Where do the integer intervals exist?

**Comment by kinxer** [comment]
Perhaps [the Range documentation](https://crystal-lang.org/docs/syntax_and_semantics/literals/range.html) could be expanded to make this clear, but

>Ranges typically involve integers, but can be created using arbitrary objects as long as they define succ (or pred for #reverse_each), to get the next element in the range, and < and ==, to know when the range reached the end.

[Source](https://crystal-lang.org/api/0.27.0/Range.html)

For this reason, it doesn't make sense to define Ranges in terms of `Z`, since the values involved need not be part of `Z`.

Furthermore, the docs are very clearly not defining Ranges in a mathematically _rigorous_ way, and the reference to mathematics is no less accurate for not being rigorous.

**Comment by Paalon** [comment]
Then, what I think it should be is `x..y # {r ∈ X | x ≦ r ≦ y}` and `x...y # {r ∈ X | x ≦ r < y}` and `X` is for abitrary iterable set.
I want this expression to be changed because this part of Japanese translation dosen't make sense. 
http://ja.crystal-lang.org/docs/syntax_and_semantics/literals/range.html

> x..y  # 右側の値を「含む」範囲です。数学的には閉区間となります: [x, y]
> x...y # 右側の値を「含まない」範囲です。数学的には左閉右開区間となります: [x, y)

> x..y # The range which "includes" the right value. In mathematically, it is closed interval: [x, y]
> x...y # The range which "does not includes" the right value. In mathematically, it is left-closed right-open interval: [x, y)

In this case, it is pointless to use the topological words. I think this is due to the ambiguous and not typical usage of mathematical word in English docs.

**Comment by straight-shoota** [comment]
I don't think there is anything actionable here per https://github.com/crystal-lang/crystal-book/issues/291#issuecomment-445271007
