### ISSUE TITLE
Document usage of annotations

### ISSUE THREAD

**Issue by Heaven31415** [crystal-lang/crystal-book#292]
This pull request introduced **annotations**: [link](https://github.com/crystal-lang/crystal/pull/6063) They used to be called **attributes**. 

This page in the crystal-book is the only one which mentions them: [link](https://github.com/crystal-lang/crystal-book/blob/master/syntax_and_semantics/attributes.md) Name of this page needs to be updated from **attributes.md** to **annotations.md**. 

Annotation list used to be fixed, but now it's not. We have two categories of annotations: those provided by the compiler (built-in) and those provided by users. 

I think it would be nice to create two separate pages, one describing compiler provided annotations (which we already have) and another about those provided by the user.

I think the article about user defined annotations should show:
- how to define an annotation
- where you can place an annotation (you can place them on top of instance variables, class variables, methods and types)
- how to query an annotation
- that you can override annotations
- a few examples of annotations (one for every possible case)
- usage examples and why you might need them
- that they are used for JSON and YAML serialization in std.

If I'm missing something or anything is wrong, tell me. This way we can make it a lot easier to write about them, especially if we have a solid plan.

If you want to find out more about annotations, check this out:
- [Allow annotations on methods](https://github.com/crystal-lang/crystal/commit/e6a6a1e8c0dd06a2cc05c70d3dac056d8c1461e1)
- [Annotations: add spec for overriding an annotation usage](https://github.com/crystal-lang/crystal/commit/c3eb6d217039a0efff065370436bbcc345be4e7a)
- [Compiler: allow annotations inside enums](https://github.com/crystal-lang/crystal/commit/8154c2d1894e3e82a28284701cd5841bf749af31)
- [Fix: annotation check failure when other annotations are present](https://github.com/crystal-lang/crystal/commit/20e7d360ffd853854dd83d763a8f56113c55cc70)

**Comment by r00ster91** [comment]
The inbuilt annotations should be removed from the docs since the documentation will be in the API docs as far as I understood. There's this PR which adds `Deprecated` annotation docs: [`#7650`](https://github.com/crystal-lang/crystal/pull/7650).

**Comment by straight-shoota** [comment]
@r00ster91 Annotations understood by the compiler should be mentioned both in the API docs and language reference. The API docs should focus on how to use them in code and the language reference on how the compiler treats them.

**Comment by Blacksmoke16** [comment]
Writing this up now, will make a PR in next few days once it's done.
