### ISSUE TITLE
I18n?

### ISSUE THREAD

**Issue by MatheusRich** [crystal-lang/crystal-book#368]
Where can I find i18n version of the docs? I'm a native portuguese speaker and want to contribute for this!

**Comment by straight-shoota** [comment]
Thanks for reaching out! Currently, there are non plans for translating the language reference to other languages. 
There are translations to Japanese http://ja.crystal-lang.org/docs/ and Taiwanese http://tw.crystal-lang.org/docs/ but they don't seem to be up to date. They're individual initiatives and there is no coordinated effort from the core team to support the translation process.

Such translations require a lot of work which is currently not available or better put to use elsewhere. Even the primary English version is still missing lot's of important content. And Crystal is still evolving at a pace, which means the reference (and thus translations) need to be constantly updated.
For these reasons I don't see much sense in investing effort into translation at the current state of things. That's IMO a task to face after 1.0 is released.

**Comment by bcardiff** [comment]
@MatheusRich you might be interested to check with @andrealmar regarding #150

**Comment by straight-shoota** [comment]
Closing. There are currently no plans for localized versions of this documentation, so nothing actionable here. 
In case someone likes to start a localization initiative, feel free to open a new issue.
