### ISSUE TITLE
Incorrect / Outdated OptionParser Syntax in CLI tutorial

### ISSUE THREAD

**Issue by craigem** [crystal-lang/crystal-book#381]
Just started learning Crystal and was following your CLI tutorial. I kept getting the following error using `OptionParser` the way it was described:

```OptionParser.parse do |parser|```

it would fail with:

```
In help.cr:4:14

 4 | OptionParser.parse do |parser|
                  ^----
Error: wrong number of arguments for 'OptionParser.parse' (given 0, expected 1)
```

After some digging around I found this example with which works:

```OptionParser.parse! do |parser|```

I do not (yet) understand the significance of the exclamation mark but with my whole 5 minutes of Crystal skills, this is how I wa able to get the example to run.

**Comment by bcardiff** [comment]
Hi @craigem, thanks for taking the time to dig into this and send a pr for the documentation.

May I know what is the output of the following command for you? `$ crystal --version`

The `OptionParser` had some refactors in the past regarding that method and that might cause the discrepance.

**Comment by craigem** [comment]
Heya @bcardiff - thanks for your response. I suspect you're probably correct. The output is:

```
$ crystal -v
Crystal 0.30.1 (1970-01-01)

LLVM: 6.0.1
Default target: x86_64-unknown-linux-gnu
```

Which is the current default [version for NixOS](https://github.com/NixOS/nixpkgs/blob/nixos-19.09/pkgs/development/compilers/crystal/default.nix#L215).

**Comment by bcardiff** [comment]
On master they already have 0.32.0 and they will upgrade to latest at some point https://github.com/NixOS/nixpkgs/pull/75545 

I'm not a nix user (yet?) so I am not sure how to suggest you download latest while still using nix.

I guess we should update the github template of this repo to advise the author to check the compiler version.

I hope the next steps on Crystal will go smoother

**Comment by craigem** [comment]
Thanks @bcardiff  - my error is clearer comparing at these two:

https://crystal-lang.org/api/0.32.1/OptionParser.html

and

https://crystal-lang.org/api/0.30.1/OptionParser.html

The `!` requirement is clearly a 30.1 behaviour. The doco is fine, I just need a more current version of crystal, for which I have means of sorting vis Nix.

Thanks!
