### ISSUE TITLE
add crystal 0.35.1 run syntax to getting-started cli project

### ISSUE THREAD

**Issue by ielm** [crystal-lang/crystal-book#414]
The getting-started CLI application docs shows running a crystal program with the syntax "crystal ./prog.cr -- --arg". This change will update the syntax to 0.35.1 (on MacOS) to run a program with "crystal run ./prog.cr -- --arg".

**Comment by ielm** [comment]
See https://github.com/ielm/crystal-book/blob/ielm-getting-started/getting_started/cli.md for the change

**Comment by straight-shoota** [comment]
This has been fixed.
