### ISSUE TITLE
Add installation guide for ARM

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal-book#42]

**Comment by HCLarsen** [comment]
I second this. There's already a lot of people talking about using this on their Raspberry Pi, myself included.

**Comment by mverzilli** [comment]
Yes, it's a great idea and the request for instructions is recurrent. We currently don't have a testing env set on a Raspberry though, so we need someone from the community to contribute this.

**Comment by HCLarsen** [comment]
@ysbaddaden , you created and host that Raspbian repository, would you be able to help us with this?

**Comment by ysbaddaden** [comment]
This is an unofficial repository, seldom maintained. There are no official testing for the ARM nor AArch64 targets, nor any official releases of the compiler.

Basically, the only information we can give would boil down to cross compile the compiler (or cross compile your app) and link it on ARM. Which is what I do for the raspbian repository.

**Comment by HCLarsen** [comment]
I can't speak for others, but I'd like that information. I haven't worked with compiled languages in a while, so my knowledge of working with compilers isn't very good.

**Comment by straight-shoota** [comment]
Installation instructions are now at https://crystal-lang.org/install/ and aarch is supportes as far as appropriate Crystal packages are available.
