### ISSUE TITLE
Documentation Request: Compiler rewrites Comparisons like a <= b <= c to a <= b && b <= c

### ISSUE THREAD

**Issue by monsterkrampe** [crystal-lang/crystal-book#510]
I came along some Crystal Code where someone used a comparison like `a == b == c` where `a,b,c` are Numbers.
I was very confused that this worked. Initially, I would have thought that the compiler does not allow this or that at least it is always `false` since even if `a == b` is `true`, `true == c` should be `false` if `c` is a Number.

I did not find anything about that in the Documentation but I finally discovered the Code for the Compiler that handles this:  
https://github.com/crystal-lang/crystal/blob/a7544b5f0f3e23d05cb4622ff4db3cbb7f1b996a/src/compiler/crystal/semantic/normalizer.cr#L100

I like the feature very much as it is really nice syntactic sugar. However, without documentation I find it rather confusing.
Maybe I just did not find this behavior in the documentation but if this is indeed not documented, I think it would be important to add it. Probably, https://github.com/crystal-lang/crystal-book/blob/master/docs/syntax_and_semantics/operators.md#comparison is a good place.  
Let me know what you think about this. I'm also happy to prepare a PR if it is indeed not documented yet and you also think that this should be added to the Docs :)

Maybe there are also some other "rewritings" done by the compiler that should be documented as well.

**Comment by beta-ziliani** [comment]
Please go ahead with the PR :-) If you do, take into consideration all the cases listed in https://github.com/crystal-lang/crystal/blob/a7544b5f0f3e23d05cb4622ff4db3cbb7f1b996a/src/compiler/crystal/semantic/normalizer.cr#L124
Thanks!
