### ISSUE TITLE
Netlify previews are broken due to missing support for Python 3.9

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal-book#540]
The recently added deploy previews are already broken because Netlify removed Python 3.9 from their build images (https://github.com/netlify/build-image/pull/611). Apparently, our mkdocs setup does not work with Python 3.8 which would be the most recent version available in the build images.

@oprypin Any idea? Can we make the plugins work with Python 3.8? The [error log](https://app.netlify.com/sites/crystal-book/deploys/6124cbb43a6c7b00932f67b4) suggests an issue with mkdocs_code_validator.

**Comment by oprypin** [comment]
Oops, it's indeed a bug that that plugin breaks on Python 3.8. I will definitely fix that this week.

**Comment by oprypin** [comment]
Where is the config for Netlify, anyway?

**Comment by straight-shoota** [comment]
The configuration is only minimal (just the build command `mkdocs build -d site --strict`) and it's configured via the netlify app UI.
But I suppose we could extract that to a config file in the repository for better accessibility.
