### ISSUE TITLE
Document the `loop` keyword

### ISSUE THREAD

**Issue by SamantazFox** [crystal-lang/crystal-book#542]
I've seen that used a ton of times across the code, but it's not mentionned in the Control expressions.

From the stdlib:
https://github.com/crystal-lang/crystal/blob/dd40a2442fa186add8a82b74edb14a90aa1dae05/spec/std/socket/unix_socket_spec.cr#L85
https://github.com/crystal-lang/crystal/blob/6a3f6b1e89be89dbe32a66a11da92d35e7790977/src/uri/punycode.cr#L71-L77

**Comment by oprypin** [comment]
> "it is highlighted as such"

That's a bug in their highlighter, then.

**Comment by SamantazFox** [comment]
> `loop` is not a keyword. It's a method implemented in stdlib: https://crystal-lang.org/api/latest/toplevel.html#loop(&)-class-method

Mmh, sure, but my remark was about the fact that `loop` is not documented in the reference book, where [`typeof`](https://crystal-lang.org/reference/syntax_and_semantics/typeof.html) is, for instance.

**Comment by oprypin** [comment]
Yes, because `typeof` is a keyword 🤔 unlike `loop`

**Comment by beta-ziliani** [comment]
I just realize that `loop` is in fact mentioned in the `while` section. I guess we just need to add a section to the tutorial with focus on iteration.

**Comment by SamantazFox** [comment]
> Yes, because `typeof` is a keyword 🤔 unlike `loop`

`typeof` is a class method, apparently: https://crystal-lang.org/api/1.1.1/toplevel.html#typeof(*expression):Class-class-method

**Comment by straight-shoota** [comment]
I think we can close this. `loop` is properly documented in the stdlib API docs.
