### ISSUE TITLE
Update Standard Library API documentation to match Language Reference

### ISSUE THREAD

**Issue by obtusedev** [crystal-lang/crystal-book#546]
Why is the style and theme of Crystal Language Reference different from Crystal Standard Library API documentation?  

The two documentation above have different themes & font making it feel inconsistent and different.  
In addition to form the Mkdoc with Material Theme is also better functionally.  
Is there a way to bring Crystal Standard Library API to use the same docs (Mkdocs Material Theme) as Crystal Language Reference?

Example:

### Crystal Language Reference (Mkdoc Material Theme)
* Clean font (Roboto & Roboto Mono) making it easier to read. (see images)
* Syntax highlighting is easier to see and more constrast. [LINK](https://user-images.githubusercontent.com/66740598/131432445-7375fd8e-1db5-4eb6-aa16-7d5dafa2dfe6.png)
* Makes better use of space e.g. documentation centered and not off to the right. [LINK](https://user-images.githubusercontent.com/66740598/131432496-6017536b-dc37-4802-8778-48cbd75da855.png)
* Better responsive layout for narrow monitors. [LINK](https://user-images.githubusercontent.com/66740598/131431678-368222d3-b531-4097-adec-e9b96c0834ec.png)

### Crystal Standard Library API (Unknown theme)
* Font harder to read as it is really thin when it comes to keywords e.g. `def` `self`. The syntax color is also faint and faded. [LINK](https://user-images.githubusercontent.com/66740598/131432804-76555989-6a98-441d-a9cd-afd8aacecb6c.png)
* Code hard to see with the syntax theme (especially the purple) and thin font combination e.g the `Array` [LINK](https://user-images.githubusercontent.com/66740598/131432919-3a781b0a-95fc-487d-9739-84a2b21afe46.png)
* Bad layout for narrow/verticle monitors. [LINK](https://user-images.githubusercontent.com/66740598/131432575-964c0c28-10bd-4dde-a70f-2670db5d5bf7.png)
  * There is no way to close the left sidebar that takes up 1/3 of screen real estate. 

This is probably not a priority and is frivolous but I figure I'll open a discussion on it for the future.
Thanks for working on Crystal and keep up the good work. Much appreciated. :+1: 

Upon futhur investigation I see this comment:

> I've recently seen some very nicely looking documentation sites made with mkdocs, particularly [mkdocs-material](https://squidfunk.github.io/mkdocs-material/). So that's defintely something I could very well see for crystal documentation. mkdocs is a tried and proven docs generator and it can have a pretty and modern look that fits with Crystal.

_Originally posted by @straight-shoota in https://github.com/crystal-lang/crystal-book/issues/261#issuecomment-729999112_

Is it possible we bring it to the Crystal Standard Library API?

**Comment by oprypin** [comment]
That is fully implemented
but most people dislike it

https://oprypin.github.io/crystal-book/api/index.html
https://github.com/oprypin/crystal-book
https://github.com/mkdocstrings/crystal - you can use it for your own projects

**Comment by straight-shoota** [comment]
The stdlib API docs are generated by the compiler command `crystal docs` and uses the standard theme.

The docs generator obvious has several issues with it, you have pointed out some of them. But there are different paths how it could evolve. As of this moment, it is not clear what the future of `crystal docs` will be.

A certain goal is to provide an easy tool for generating (API) documentation for any Crystal project.

Using mkdocs as suggested by @oprypin  is not quite straightforward because it requires an additional toolchain consisting of Python and mkdocs with several plugins. It's definitely an option if you don't mind setting that up.
