### ISSUE TITLE
[Documentation] Add "from language xyz to crystal" guides to the OFFICIAL documentation

### ISSUE THREAD

**Issue by rubyFeedback** [crystal-lang/crystal-book#579]
Hey crystal folks,

I refer largely to https://crystal-lang.org/reference/.

I know ruby very well, but I still don't know crystal that well. In particular the
type system is unknown to me.

From this use case, I'd love an official guide, a bit like a blog entry BUT
integrated into the main website (I don't want to chase down blog entries
that may disappear).

Something like "from ruby to crystal" and specifically the TYPE system
because this is the one that confuses me the most. When to use types,
how, and how that may change how you think about when writing
crystal code. I can manually convert my ruby code, but first I have to
understand the type situation, and for this I would LOVE to read an
official guide, as that would help me keep my time investment minimal
(too many different tasks for me to handle, so I'd love if I could just
focus on one aspect, such as types, and then go from there via
trial-and-error. I am fine with trial-and-error on my own but I need
a "starter" help like for a car engine - that's how my brain works.
This is why I'd love a separate article that could focus on types,
but it can also focus on other aspects related to ruby-versus-crystal;
and perhaps for all major languages out there e. g. "from python
to crystal".)

**Comment by straight-shoota** [comment]
Related: #470

**Comment by a-alhusaini** [comment]
@rubyFeedback This page is labelled Crystal for Rubyists. It is precisely what you want. If any particular point of comparison between the two languages pop up we'd happily clear it up in the crystal forum and or the crystal discord server. Cheers!
https://crystal-lang.org/reference/1.8/crystal_for_rubyists/index.html

@straight-shoota could you close this issue

**Comment by Blacksmoke16** [comment]
FWIW I think this issue was for languages _other_ than Ruby. E.g `Crystal for Pythonists` or whatever. So it's not entirely resolved just by having one for Ruby. Granted having one for _every_ language might be a bit out of scope regardless...

**Comment by straight-shoota** [comment]
Yeah, I'm not sure what the exact scope of this issue was, but I feel it's primarily about Ruby where we already have a guide.
Adding similar guides for other languages might be good, but that's just a wish, not an actionable item that we could keep this open for.
