### ISSUE TITLE
[Documentation] Provide a guide for ruby users, aka a ruby-to-crystal guide, ideally linked in via: https://crystal-lang.org/docs/

### ISSUE THREAD

**Issue by rubyFeedback** [crystal-lang/crystal-book#580]
I would like to propose to providing a guide that focuses on ruby users who know ruby very well already.

Something that makes it possible to understand the DIFFERENCES in crystal.

In theory people can read the documentation and learn on their own, but some users are very very
lazy. I am one of those!

For those lazy users, a succinct how-to-guide would be super useful. It does not have to be super-long,
by the way; just a medium sized article that focuses on the most important differences, and specifically
has "expert ruby users" as main target audience. This should be a collaborative guide that can be
easily extended by different crystal users, but please not the github wiki - the github wiki is, unfortunately,
really really bad. (Github issues on the other hand are super-useful.)

PS: For the length, I recommend a "normal" sized article on medium.com. While I hate medium, the
SIZE of the articles there is quite ok, so the aim of this proposal is to aim for a similarly sized, but still
succinct, article in this regard as well.

**Comment by HertzDevil** [comment]
The book is intended as a general guide to programming, and in my opinion actually conflicts with some of our existing guides and tutorials, whereas the wiki page focuses on language feature and standard library differences; the two have very different purposes.

I think we should expand upon the latter and also incorporate things that are in Ruby 3. Two important ones are [`Fiber::SchedulerInterface`](https://ruby-doc.org/core-3.0.0/Fiber/SchedulerInterface.html), which brings their concurrency primitives closer to ours, and [TypeProf](https://github.com/ruby/typeprof), that can technically express concepts like generics and overloading.

**Comment by beta-ziliani** [comment]
The wiki paged was moved to the book. We can close this one.
