### ISSUE TITLE
There are many crystalshards.xyz in documents which point to a non-exists site.

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal-book#612]
Don't sure if this is should be `https://crystalshards.org/`, if it is, i can create a PR to fix this.

**Comment by straight-shoota** [comment]
We should apply #558 to the remaining occurences of explicit links to crystalshards.xyz

**Comment by zw963** [comment]
Yes, at least for me, i consider `https://crystalshards.xyz` is one offline site, until today.

**Comment by zw963** [comment]
Maybe list all known available shards site is better than just xyz.

e.g.

** https://shardbox.org/
** https://crystalshards.org/
** https://shards.info/

**Comment by straight-shoota** [comment]
Yes we're doing that via reference to https://crystal-lang.org/community/#shards

**Comment by zw963** [comment]
> Yes we're doing that via reference to https://crystal-lang.org/community/#shards

Yeah, i saw it.
