### ISSUE TITLE
Documentation error about Operator Precedence for `==` and `<`

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal-book#615]
Check [operator-precedence](https://crystal-lang.org/reference/1.4/syntax_and_semantics/operators.html#operator-precedence) section, see following screenshot too.

![image](https://user-images.githubusercontent.com/549126/170828111-bd20150d-f2e4-4fd9-a015-0a1190603dfe.png)

We say,  the precedence of `==` is more higher than `<`, if this is correct, following should result in compilation exception.

```rb
x = 20

p(x == 100 < 200)
# if document is correct, it should be (x == 100) < 200, right?
```

But it not, it behavior as

```
x  = 20
p(x == (100 < 200))
# this behavior same as Ruby too.
```

So, i guess this just a typo?

**Comment by straight-shoota** [comment]
What you're observing here is an effect of operator chain normalization. This is explained in the docs: https://crystal-lang.org/reference/1.4/syntax_and_semantics/operators.html#chaining-equality-and-comparison

You can observe that this is happening here by using the `p!` macro to print the value as it will also show the expanded expression:
```cr
p! 20 == 100 < 200 # (20 == 100) && 100 < 200 # => false
```

**Comment by zw963** [comment]
> as it will also show the expanded expression:

So Cool feature!
