### ISSUE TITLE
Typo in example of method arguments

### ISSUE THREAD

**Issue by axvm** [crystal-lang/crystal-book#633]
https://github.com/crystal-lang/crystal-book/blob/9f73ed072921d9c6fbf864b1a0125ff41718623f/docs/syntax_and_semantics/default_values_named_arguments_splats_tuples_and_overloading.md?plain=1#L22-L23

correct me if i am wrong but named parameters using `:`, not `=`

**Comment by HertzDevil** [comment]
This is a def parameter list, not a call argument list, so `=` means a default parameter value here
