### ISSUE TITLE
make serve is broken

### ISSUE THREAD

**Issue by 4ndyfix** [crystal-lang/crystal-book#658]
Hi,
The newest book doesn't work for me anymore.
It seems to be a python problem:

make serve
python3 -m venv .venv
.venv/bin/pip install -q --no-deps -r requirements.txt && touch .venv/bin/mkdocs
  ERROR: Command errored out with exit status 1:
   command: /home/andi/test/crystal-book/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6f785y2o/mkdocs-redirects/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6f785y2o/mkdocs-redirects/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ydh12hcb
       cwd: /tmp/pip-install-6f785y2o/mkdocs-redirects/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for mkdocs-redirects
.venv/bin/mkdocs serve
Traceback (most recent call last):
  File ".venv/bin/mkdocs", line 5, in <module>
    from mkdocs.__main__ import cli
  File "/home/andi/test/crystal-book/.venv/lib/python3.8/site-packages/mkdocs/__main__.py", line 15, in <module>
    from mkdocs import __version__, config, utils
  File "/home/andi/test/crystal-book/.venv/lib/python3.8/site-packages/mkdocs/config/__init__.py", line 1, in <module>
    from mkdocs.config.base import Config, load_config
  File "/home/andi/test/crystal-book/.venv/lib/python3.8/site-packages/mkdocs/config/base.py", line 25, in <module>
    from mkdocs import exceptions, utils
  File "/home/andi/test/crystal-book/.venv/lib/python3.8/site-packages/mkdocs/utils/__init__.py", line 39, in <module>
    from importlib_metadata import EntryPoint, entry_points
ModuleNotFoundError: No module named 'importlib_metadata'
make: *** [Makefile:20: serve] Fehler 1

**Comment by straight-shoota** [comment]
Works for me. I also checked with a clean `ubuntu:22:10` image and installed packages `make`, `python3`, `python3.10-venv`.

Maybe your Python installation is missing the `wheel` package. Try `pip install wheel`.

**Comment by friscodelrosario** [comment]
> Works for me. I also checked with a clean `ubuntu:22:10` image and installed packages `make`, `python3`, `python3.10-venv`.
> 
> Maybe your Python installation is missing the `wheel` package. Try `pip install wheel`.

make serve broke for me for missing the importlib_metadata module

```
frisco@frisco-520-1047c:~/crystal-book$ make serve
.venv/bin/mkdocs serve
Traceback (most recent call last):
  File ".venv/bin/mkdocs", line 5, in <module>
    from mkdocs.__main__ import cli
  File "/home/frisco/crystal-book/.venv/lib/python3.8/site-packages/mkdocs/__main__.py", line 15, in <module>
    from mkdocs import __version__, config, utils
  File "/home/frisco/crystal-book/.venv/lib/python3.8/site-packages/mkdocs/config/__init__.py", line 1, in <module>
    from mkdocs.config.base import Config, load_config
  File "/home/frisco/crystal-book/.venv/lib/python3.8/site-packages/mkdocs/config/base.py", line 25, in <module>
    from mkdocs import exceptions, utils
  File "/home/frisco/crystal-book/.venv/lib/python3.8/site-packages/mkdocs/utils/__init__.py", line 39, in <module>
    from importlib_metadata import EntryPoint, entry_points
ModuleNotFoundError: No module named 'importlib_metadata'
make: *** [Makefile:20: serve] Error 1
```

But the importlib_metadata module is installed.

```
frisco@frisco-520-1047c:~/crystal-book$ python3 -m pip install importlib_metadata
Requirement already satisfied: importlib_metadata in /home/frisco/.local/lib/python3.8/site-packages (6.6.0)
Requirement already satisfied: zipp>=0.5 in /home/frisco/.local/lib/python3.8/site-packages (from importlib_metadata) (3.15.0)
```

And neither is the wheel package missing.

```
frisco@frisco-520-1047c:~/crystal-book$ python3 -m pip install wheel
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.34.2)
```

**Comment by 4ndyfix** [comment]
After a general upgrade from Ubuntu 20.04 LTS to Ubuntu 22.04 LTS
the python problem was gone for me.

**Comment by beta-ziliani** [comment]
as per https://github.com/crystal-lang/crystal-book/issues/658#issuecomment-1561897060 I understand this is solved
