### ISSUE TITLE
Add Korean translations

### ISSUE THREAD

**Issue by linterpreteur** [crystal-lang/crystal-book#69]
I'm currently working on translation of this repo to Korean. I'll keep working on that even if you won't accept the PR, mainly because I really love this language, but I want to make sure if my translations would be merged to this official repo.

I acknowledge that Crystal lang is still developping and therefore there are many changes to the document. I've updated with 5 commits made to the original repo after I forked it.

My former open source translation contributions include [timeago.js](https://github.com/hustcc/timeago.js), [Learn X in Y minutes](https://github.com/adambard/learnxinyminutes-docs), [Shattered Pixel Dungeon](https://www.transifex.com/shattered-pixel/shattered-pixel-dungeon/dashboard/), and [Latern](https://www.transifex.com/otf/). The forked repo is <https://github.com/linterpreteur/crystal-book>.

Thanks.

**Comment by sdogruyol** [comment]
@linterpreteur thank you and welcome 🎉

**Comment by humboldtux** [comment]
Just to let you know that i finished a (rough) [french translation](https://github.com/Crystal-French) of the Crystal book. Still need to translate the official website and figure out how to host it.

**Comment by mverzilli** [comment]
@linterpreteur thank you for your work! Translations are very welcome and we'll be happy to point an official subdomain to it when you are ready to share them with the rest of the world :). We did it with other languages, for example see this thread about Russian translations: https://groups.google.com/forum/#!searchin/crystal-lang/translation%7Csort:relevance/crystal-lang/OyJR4lW3Vck/1JZPcbOsDwAJ

If you need any help, please send an email to Crystal's Google Group, I think it's the more appropriate to discuss this. 

@humboldtux: likewise. Having French translations would be great! When you feel like publishing them send an email to the Google Group and we'll discuss how to make them available.
