### ISSUE TITLE
make serve

### ISSUE THREAD

**Issue by overtube** [crystal-lang/crystal-book#700]
**mkdocs serve**
```
Error: MkDocs encountered an error 
parsing the configuration file: 
while constructing a Python object
cannot find module 'materialx.emoji' 
(No module named 'materialx')
  in "/home/ui/Templates/crystal-book/mkdocs.yml", 
line 83, column 20
make: *** [Makefile:19: serve] Error 1
```

**Comment by overtube** [comment]
**also I make** 
`pip install materialx` 
`pipx install materailx`
and giving the same error, lol what how is actualy working?

**Comment by overtube** [comment]
**also I seen that** 

`pip install *somepackage`
`error: externally-managed-environment`

```
× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
```
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by overtube** [comment]
and also I have `python-pipx`

**Comment by overtube** [comment]
whay not some simple way for serve is using docs 
like that maybe, but made built-in
`https://github.com/SuperPaintman/serve`

**Comment by straight-shoota** [comment]
The Makefile expects an operational Python environment with all dependencies available.
You should typically be able to set that up with `pip install -r requirements.txt` (see https://github.com/crystal-lang/crystal-book#building-and-serving-locally).
If that doesn't work for you, I suspect some configuration issue on your system.

Alternatively you could try the devenv environment: https://github.com/crystal-lang/crystal-book#devenv-environment

> whay not some simple way for serve is using docs 
> like that maybe, but made built-in
> `https://github.com/SuperPaintman/serve`

`make serve` does not just serve content over HTTP it also *generates* the content before that. Using a standalone HTTP server would be possible, but you still need to build the site first. And the way `make serve` fails, I wouldn't expect `make build` to work any better.

**Comment by overtube** [comment]
all work if I passing flag --break-system-packages when make installing from requiremnets.txt but fail if I make it from working system, but if I use else virtual environment tools like venv pip or pipx, I have that error

**Comment by straight-shoota** [comment]
That seems to be a problem with your Python configuration then, where perhaps system packages conflict with pip and venv.
