### ISSUE TITLE
Update "Instance variables type inference" section to reflect ivars rules

### ISSUE THREAD

**Issue by mverzilli** [crystal-lang/crystal-book#74]
See: https://github.com/crystal-lang/crystal/issues/3894

**Comment by robacarp** [comment]
This seems like it is resolved now. The page referenced in the original issue is probably [syntax and semantics/type inference](https://crystal-lang.org/docs/syntax_and_semantics/type_inference.html) and looks to contain a nice ordered list which closely matches the description the compiler outputs.

**Comment by mverzilli** [comment]
Right, thanks for pointing out!
