### ISSUE TITLE
Refer to this book as "Language Reference" 

### ISSUE THREAD

**Issue by mverzilli** [crystal-lang/crystal-book#78]
Review the whole book and change any mention to itself to "Language Reference"

**Comment by WildYorkies** [comment]
If no one has started this, I can work on it 👍

**Comment by WildYorkies** [comment]
https://github.com/crystal-lang/crystal-book/pull/86

**Comment by mverzilli** [comment]
Closed via https://github.com/crystal-lang/crystal-book/pull/171
