### ISSUE TITLE
Add French Translations

### ISSUE THREAD

**Issue by tamdaz** [crystal-lang/crystal-book#781]
Hello,
I wonder if it is possible to add French translations to this project.
And once we've finished creating this project in French, what are the procedures for making this documentation accessible to everyone?
I'm interested in this programming language, which is still developing.

**Comment by straight-shoota** [comment]
Thanks for your interest in helping with localization.

At this point however, we do not consider this a priority in the Crystal team. Improving the primary English version and keeping it up to date is already enough of a challenge and we intent to prioritize on that.

So any work on translations would need to be community driven, with limited support from the Core Team.

Ref. #368, https://github.com/crystal-lang/crystal-website/issues/296
