### ISSUE TITLE
syntax_and_semantics &&= and ||= explanation

### ISSUE THREAD

**Issue by WildYorkies** [crystal-lang/crystal-book#81]
I need a better explanation of

```crystal
local ||= 1 # same as: local || (local = 1)
local &&= 1 # same as: local && (local = 1)
```

Wouldn't this example code make more sense as

```crystal
local ||= 1 # same as: local = local || 1
local &&= 1 # same as: local = local && 1
```

I'm still not sure of the use case for `&&=`, but I'm pretty sure my comments make more sense than the original.

Am I way off here?

**Comment by mverzilli** [comment]
The current example matches the current behavior, the one you suggest doesn't:

```crystal
foo = 2
local = nil
local = local && (foo = 1)
p local #=> nil (local is nil because nil is falsey, so the && evaluation stops there)
p foo #=> 2 (foo is still 2 because the second clause of the && isn't executed)

local = 2
local = local && 1
p local #=> 1 local was 2, which is truthy, so the && eval the second clause, which is 1. The && expression evals to 1 and is asigned to local.
```

I introduce a second variable `foo` to make differences more explicit.

**Comment by mverzilli** [comment]
The value of local at the end is the same in both cases, but the behavior is not. The current example will not overwrite `local` if the clause short-circuits. It's a bit difficult to see it in code, but if you introduce a second variable the difference becomes more apparent:

```crystal
local = 1
local || (foo = 5)
p local                  #=> 1
p foo                    #=> nil

local = 1
foo = local || 5
p local                  #=> 1
p foo                    #=> 1
```
