### ISSUE TITLE
var.is_a? when combined with ||, using the same var

### ISSUE THREAD

**Issue by WildYorkies** [crystal-lang/crystal-book#82]
There is this example in the book:

```crystal
if a.is_a?(String) && b.is_a?(Number)
  # here a is a String and b is a Number
end
```

But what about using `||` in this scenario with the same variable?

```crystal
if a.is_a?(String) || a.is_a?(Number)
  # There is no guarantee that a is bound to anything?
end
```

**Comment by RX14** [comment]
`a` would be a `String | Number`. Why not try it yourself: https://carc.in/#/r/1oal

**Comment by WildYorkies** [comment]
Right. So it would be a pointless thing to do, as you still wouldn't know what `a` is.

I suppose `.responds_to?` would be a better thing to do.
